/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppWithdrawRouteImport } from './routes/app.withdraw'
import { Route as AppTasksRouteImport } from './routes/app.tasks'
import { Route as AppServiceRouteImport } from './routes/app.service'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppDepositRouteImport } from './routes/app.deposit'
import { Route as AppBankRouteImport } from './routes/app.bank'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin.withdrawals'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ApiPublicGgpixWebhookRouteImport } from './routes/api/public/ggpix/webhook'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppWithdrawRoute = AppWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppServiceRoute = AppServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppDepositRoute = AppDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => AppRoute,
} as any)
const AppBankRoute = AppBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => AppRoute,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicGgpixWebhookRoute = ApiPublicGgpixWebhookRouteImport.update({
  id: '/api/public/ggpix/webhook',
  path: '/api/public/ggpix/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/register': typeof RegisterRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/app/bank': typeof AppBankRoute
  '/app/deposit': typeof AppDepositRoute
  '/app/history': typeof AppHistoryRoute
  '/app/profile': typeof AppProfileRoute
  '/app/service': typeof AppServiceRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/public/ggpix/webhook': typeof ApiPublicGgpixWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/app/bank': typeof AppBankRoute
  '/app/deposit': typeof AppDepositRoute
  '/app/history': typeof AppHistoryRoute
  '/app/profile': typeof AppProfileRoute
  '/app/service': typeof AppServiceRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/api/public/ggpix/webhook': typeof ApiPublicGgpixWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/register': typeof RegisterRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/app/bank': typeof AppBankRoute
  '/app/deposit': typeof AppDepositRoute
  '/app/history': typeof AppHistoryRoute
  '/app/profile': typeof AppProfileRoute
  '/app/service': typeof AppServiceRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/public/ggpix/webhook': typeof ApiPublicGgpixWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/register'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/app/bank'
    | '/app/deposit'
    | '/app/history'
    | '/app/profile'
    | '/app/service'
    | '/app/tasks'
    | '/app/withdraw'
    | '/admin/'
    | '/app/'
    | '/api/public/ggpix/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/app/bank'
    | '/app/deposit'
    | '/app/history'
    | '/app/profile'
    | '/app/service'
    | '/app/tasks'
    | '/app/withdraw'
    | '/admin'
    | '/app'
    | '/api/public/ggpix/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/register'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/app/bank'
    | '/app/deposit'
    | '/app/history'
    | '/app/profile'
    | '/app/service'
    | '/app/tasks'
    | '/app/withdraw'
    | '/admin/'
    | '/app/'
    | '/api/public/ggpix/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ApiPublicGgpixWebhookRoute: typeof ApiPublicGgpixWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/withdraw': {
      id: '/app/withdraw'
      path: '/withdraw'
      fullPath: '/app/withdraw'
      preLoaderRoute: typeof AppWithdrawRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/service': {
      id: '/app/service'
      path: '/service'
      fullPath: '/app/service'
      preLoaderRoute: typeof AppServiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/deposit': {
      id: '/app/deposit'
      path: '/deposit'
      fullPath: '/app/deposit'
      preLoaderRoute: typeof AppDepositRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bank': {
      id: '/app/bank'
      path: '/bank'
      fullPath: '/app/bank'
      preLoaderRoute: typeof AppBankRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/ggpix/webhook': {
      id: '/api/public/ggpix/webhook'
      path: '/api/public/ggpix/webhook'
      fullPath: '/api/public/ggpix/webhook'
      preLoaderRoute: typeof ApiPublicGgpixWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppBankRoute: typeof AppBankRoute
  AppDepositRoute: typeof AppDepositRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppProfileRoute: typeof AppProfileRoute
  AppServiceRoute: typeof AppServiceRoute
  AppTasksRoute: typeof AppTasksRoute
  AppWithdrawRoute: typeof AppWithdrawRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBankRoute: AppBankRoute,
  AppDepositRoute: AppDepositRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppProfileRoute: AppProfileRoute,
  AppServiceRoute: AppServiceRoute,
  AppTasksRoute: AppTasksRoute,
  AppWithdrawRoute: AppWithdrawRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ApiPublicGgpixWebhookRoute: ApiPublicGgpixWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
